### ISSUE TITLE
Cannot find module: index

### ISSUE THREAD

**Issue by kov1fer** [anvilco/spectaql#258]
When I"m trying to run spectaql, the floowing error has appeared:

![image](https://user-images.githubusercontent.com/70896378/161258670-41c4abcb-d1a9-42ab-b325-966ddbd7c72f.png)

What should I do to eliminate this error?

**Comment by newhouse** [comment]
@kov1fer can you provide me a simple/sanitized copy of your `config.yml`? 

The "doubling up" of the full path in the image suggests that it probably has to do with path resolution and the fact that you appear to be on Windows and not *nix.

![image](https://user-images.githubusercontent.com/2524009/161311010-c9dacb61-1eda-49d7-8db7-dcc65fc53ed7.png)

**Comment by newhouse** [comment]
Also, what version of Node are you on?

**Comment by newhouse** [comment]
I think I just fixed the problem in `1.0.1`...can you try installing that version?

**Comment by kov1fer** [comment]
Unfortunately your solution isn't solved the issue. About one and a half month ago, I have been able to use this fantastic tool, but now I cannot. Please, examine the real problem of this issue.

![image](https://user-images.githubusercontent.com/70896378/161767696-f4b03030-0e49-41fc-82b3-3168cf6b5c83.png)

**Comment by newhouse** [comment]
@kov1fer 
Can you provide your config and any other files used by it, please?

**Comment by newhouse** [comment]
@kov1fer can you try using `spectaql@1.2.0-0` and see if that does it for you?  And if that doesn't work, can you try `spectaql@1.1.0-0`?

**Comment by kov1fer** [comment]
You're great. Now, it works fine. Thank you for your support. :)

**Comment by newhouse** [comment]
Fixed in `1.0.11` via https://github.com/anvilco/spectaql/pull/288
