### ISSUE TITLE
Metdata for "enumValues" not working

### ISSUE THREAD

**Issue by glinskyc** [anvilco/spectaql#704]
Despite trying combinations of settings for `enumsDocumentedDefault` and `enumDocumentedDefault`, nothing seems to allow the metadata in `"enumValues"` to be used.  

For example, your example `metadata.json` includes the following, but the `EMPIRE` value still gets documented.  In my testing, vice versa is also true, i.e. `"documented": true` has no effect when wanting to document only certain values of an enum, while hiding all others (an additional config variable may be appropriate to account for that use case?).

```
"ENUM": {
    "EpisodeEnum": {
      "enumValues": {
        "EMPIRE": {
          "documentation": { "undocumented": true }
        }
      }
    }
  },
```

**Comment by glinskyc** [comment]
Implementing these variables could help address the use case of documented / undocumented for individual enum values.

```yaml
  # Whether to document an individual Enum Value, in the absence of a metadata directive
  # Default: true
  enumValueDocumentedDefault: true
  # Hide any enumValues of undocumented enums so as not to reference something that seemingly does not exist.
  # Default: true
  hideEnumValuesOfUndocumentedType: true
```

**Comment by silverman63** [comment]
+1'ing this. An example of where this could be valuable is something like country, where the docs would end up double the length with very little insight gained. 

Collapsable would be a valid alternate IMo as well.

**Comment by SympleSynz** [comment]
I believe the fix for this issue/bug would also fix https://github.com/anvilco/spectaql/issues/855
EnumValue doesn't appear in the `hideFields` function

**Comment by newhouse** [comment]
Going to have a look at this in the next few days if I can. Busy with travel right now.

**Comment by newhouse** [comment]
This should be fixed in the latest `main`, as well as in `spectaql@2.2.0-beta.0`.

There is a dependency with a busted semver that I'm waiting for them to resolve before publishing completely as `2.2.0`.

Can you confirm this works?

@SympleSynz @glinskyc @silverman63 @wilau2

**Comment by SympleSynz** [comment]
@newhouse Confirmed that the above version worked and removed the ENUM_VALUE we didn't want published

**Comment by glinskyc** [comment]
This is still not working when I test it with either the latest v2.9 or v3.  I've tested it by specifying the metadata directly, like the example in my original post, where a specific enum is being specified as undocumented.  I've also tried using the spectaql directive to undocument a specific enum value, as mentioned in issue #855, but that also isn't working for me (getting error: Unsupported typeDef).
